### ISSUE TITLE
Some problems with the search functionalities

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#106]
Suppose I have a task 'go to night school', the following will show no results (those near-match could be considered correct to have no results depending on your design):
'n\* school'
'nite school'
'night skool'
'nite skool'

My suggested behavior for '*' when it's standing alone (not immediately next to any non-white space character) is just to ignore. Otherwise it's matched to any sequence of non-whitespace characters

**Comment by AnHaNguyen** [comment]
for the first 1, since we use google convention and do not support using asterisks for single letters, hence it should return no result.
for the other 3, it comes from my near match convention, which is rather strict now. So I can reduce it a little bit so the skool can be matched

**Comment by ndt93** [comment]
Hmm I suppose for the first one, the \* is in the place of 'ight' so it's multiple characters?

**Comment by ndt93** [comment]
otherwise if the '*' is only for the whole word then it's not very useful as we already search other words on a token basis

**Comment by AnHaNguyen** [comment]
yeah, but if " \* " can be used for multiple characters, then some cases might result in a lot of unrelevant results, like if u try to search " \* e \* "

**Comment by ndt93** [comment]
If the '_' is standalone then you can just ignore it since it's not useful in that case. So "_ e *" would mean searching for tasks of which contents as a word 'e'

**Comment by AnHaNguyen** [comment]
Not sure if I get what u mean, so you're saying that " \* " standing alone for a single word is not needed but " \* " rather be used to represent multiple characters like "n\* " would return "night"?

**Comment by ndt93** [comment]
Yup. Otherwise the standalone '*' will match everything

**Comment by AnHaNguyen** [comment]
ok, so I guess I'll change my wildcard back to the original one
