### ISSUE TITLE
Resizing window does not resize input text box

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#57]
Possible alternative: disallow window resize

**Comment by sharminelow** [comment]
I have managed to resize the inputbox when you expand the window size. However, it doesn't work when you try to shrink it. Do you want to accept this solution or would disabling window resize be a better solution?

**Comment by ndt93** [comment]
Ok I think that's fine. Users will likely want to expand rather than shrinking. Shrinking is not usually fully supported anyway (you can try it with the facebook website for example)
