### ISSUE TITLE
NullPointerException when content of setting.txt is empty

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#60]

**Comment by bihuutue** [comment]
Fixed the bug that displays NullPointerException when content of setting.txt is empty.
Also fixed the bug feature where the default task.son, if existed at program boot-up, will overwritten instead of read out!

**Comment by ndt93** [comment]
I still got the exception when I clear content of setting.txt myself and try to add something in the GUI
