### ISSUE TITLE
Wildcard search not working in some cases involving '?' character

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#62]
How to replicate: add in "do homework" task -> search for "ho?ework" -> result is empty but it shouldn't be

**Comment by AnHaNguyen** [comment]
oh i thought we have to search "*ho?ework" to return "do homework"?

**Comment by AnHaNguyen** [comment]
but anyways I fixed that bug

**Comment by ndt93** [comment]
Yup, if we search "ho?ework" then one of the results should be "do homework" but I got an empty result
