### ISSUE TITLE
Undo multiple times results in unexpected behavior

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#66]
Example: Delete a task then undo multiple times will result in the same task being added the same number of times. As a result, deleting more than 1 of the repeated tasks which are incorrectly added back by the undo ends up with more buggy behavior.

**Comment by AnHaNguyen** [comment]
we can leave undo multiple times to later version if u want

**Comment by ndt93** [comment]
We are not implementing multiple undo, but this is a bug when I use undo multiple times then there are weird behaviors. So after undo is invoked once, it should be disabled until the next operation on storage is available

**Comment by AnHaNguyen** [comment]
ok i got it, so it will return false for multiple undos
