### ISSUE TITLE
Storage's API to get the current tasks file path

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#73]
User may want to know the current path to the task file. So Logic need to handle a command to show user the path which needs to get the path from Storage

**Comment by AnHaNguyen** [comment]
ok getPath() return String

**Comment by AnHaNguyen** [comment]
but for default path, it only returns "task.json" instead of "C:....\task.json", is it good enough?

**Comment by ndt93** [comment]
Hmm preferably the full path for all cases. Is it possible?

**Comment by AnHaNguyen** [comment]
i will discuss with Tue about that, but not sure we can deliver by tonight

**Comment by ndt93** [comment]
Ok no problem :)
