### ISSUE TITLE
Cannot delete done tasks

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#85]
You guys store the done tasks separately from other tasks so the delete doesn't work with the done tasks . I suggested storing them together and differentiate by the done attribute. But you are free to implement however you want, as long as it works

**Comment by AnHaNguyen** [comment]
ok, so I will use only taskList for both done and undone tasks. Query() to return whole taskList, getDone() to return only done tasks, getUndone() to return undone tasks

**Comment by AnHaNguyen** [comment]
so now you have to use getUndone() rather than query() to display all undone tasks in GUI

**Comment by ndt93** [comment]
Oh Nooo, can I use query to get all undone tasks? Otherwise, there will be a lot of little changes here and there since after each operation, I will use query to display updated tasks list

**Comment by AnHaNguyen** [comment]
ok i'll change it, so something like queryAll() will display all done and undone tasks, if you might need it in the future

**Comment by ndt93** [comment]
Thanks :)
