### ISSUE TITLE
Visual cue to differentiate unconfirmed tasks

### ISSUE THREAD

**Issue by ndt93** [cs2103jan2015-w13-3j/main#86]

**Comment by sharminelow** [comment]
I thought it was agreed to have a '?' appended behind

**Comment by ndt93** [comment]
Yup. This is just used for reminder purpose. You can close it if you want to.

**Comment by sharminelow** [comment]
Would the ? be appended at the GUI level or storage level?

**Comment by ndt93** [comment]
Both are possible. But I think it's better on the GUI level since it's for the purpose of visual feedback. And when a task is confirmed, it can be easily changed since the question mark is not attached to the task on the low-level storage
